algoritmo "Condicinal"

var
nome: caractere

inicio
// condicional , utiliza-se booleno - logico
// senao / else - não é obrigatorio
//OPERADORES RELACIONAIS
// >  maior 
// < menor 
// >= maior ou igual
// <= menor ou igual
// = (<-) ATRIBUIÇÃO
// == comparação simples (compara conteudo)
// === comparação completa(comparar conteudo e tipo)
// != (não é igual)



nome <- "Caio"

se (nome = "Caio") entao
//condição alinhada
escreval ("Você é Lindo "+nome)
 senao
  se (nome = "Matheus") entao
    escreval("Boa boa do "+nome)
  senao
    escreval ("Você é muito paia "+nome)
 
 
 fimse
  fimse
fimalgoritmo